/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;


import java.awt.Color;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CHETHANA
 */
public class grnlist extends javax.swing.JFrame {
 UniversalMethod u = new UniversalMethod();
    public static int idsearch;
    public static stock st;
    /**
     * Creates new form grnlist
     */
    public grnlist() {
        initComponents();
          systemLogger.initLogger(grnlist.class).info("Open Grnlist Frame");
          u.imageMethod(background, home_la_uesr_image, doctor_la_login_use_name, agent_la_home_img, login_la_mini, login_la_cloce, grn_la_enter);
        u.imageMethod("/img/category.png",grn_la_print);
          u.imageMethod("/img/search.png", supplier_la_search );
             u.imageMethod("/img/update.png", supplier_la_update );
            u.imageMethod("/img/grnitem1.png", grn_la_listofgrnFrame_open);
              u.imageMethod("/img/newB.png", grn_la_new);
              UniversalMethod.TimeMethod(agent_la_date,agent_la_time);
              doctor_la_login_use_name.setText(UniversalMethod.getLogUser());
              
        agent_la_home_img.setVisible(false);
        cleareFields();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel23 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox_Supplier_name = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        tx_pay = new javax.swing.JTextField();
        jDateChooser_cd = new com.toedter.calendar.JDateChooser();
        agent_la_home_img = new javax.swing.JLabel();
        grn_la_enter = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        login_la_mini = new javax.swing.JLabel();
        tx_grn_number = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        login_la_cloce = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_grn = new javax.swing.JTable();
        tx_gen_time = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jComboBox_payroal = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        grn_la_listofgrnFrame_open = new javax.swing.JLabel();
        agent_la_time = new javax.swing.JLabel();
        tx_gen_date = new javax.swing.JTextField();
        agent_la_date = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        grn_la_print = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        doctor_la_login_use_name = new javax.swing.JLabel();
        grn_la_new = new javax.swing.JLabel();
        grn_tx_barcode = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        home_la_uesr_image = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        grn_la_barcode = new javax.swing.JLabel();
        tx_total = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        tx_balance = new javax.swing.JTextField();
        jComboBox_status = new javax.swing.JComboBox();
        supplier_la_search = new javax.swing.JLabel();
        supplier_la_update = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1376, 768));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1376, 768));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel23.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Pay");
        jLabel23.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel23);
        jLabel23.setBounds(590, 180, 120, 30);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText(":");
        jLabel9.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel9);
        jLabel9.setBounds(160, 80, 30, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(":");
        jLabel5.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(160, 130, 30, 30);

        jComboBox_Supplier_name.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox_Supplier_name.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jComboBox_Supplier_name.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox_Supplier_name.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A" }));
        jComboBox_Supplier_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox_Supplier_nameKeyPressed(evt);
            }
        });
        getContentPane().add(jComboBox_Supplier_name);
        jComboBox_Supplier_name.setBounds(190, 130, 320, 33);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText(":");
        jLabel11.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel11);
        jLabel11.setBounds(160, 180, 30, 30);

        tx_pay.setBackground(new java.awt.Color(255, 255, 255));
        tx_pay.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tx_pay.setForeground(new java.awt.Color(0, 0, 0));
        tx_pay.setText("jTextField1");
        tx_pay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tx_payKeyPressed(evt);
            }
        });
        getContentPane().add(tx_pay);
        tx_pay.setBounds(730, 180, 180, 33);

        jDateChooser_cd.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooser_cd.setForeground(new java.awt.Color(0, 0, 0));
        jDateChooser_cd.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jDateChooser_cd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jDateChooser_cdKeyPressed(evt);
            }
        });
        getContentPane().add(jDateChooser_cd);
        jDateChooser_cd.setBounds(1140, 90, 180, 29);

        agent_la_home_img.setText("jLabel1");
        agent_la_home_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agent_la_home_imgMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                agent_la_home_imgMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                agent_la_home_imgMouseExited(evt);
            }
        });
        getContentPane().add(agent_la_home_img);
        agent_la_home_img.setBounds(600, 5, 80, 30);

        grn_la_enter.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        grn_la_enter.setForeground(new java.awt.Color(0, 0, 0));
        grn_la_enter.setText("Enter");
        grn_la_enter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grn_la_enterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                grn_la_enterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                grn_la_enterMouseExited(evt);
            }
        });
        getContentPane().add(grn_la_enter);
        grn_la_enter.setBounds(400, 330, 120, 40);

        jLabel24.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText(":");
        jLabel24.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel24);
        jLabel24.setBounds(710, 180, 30, 30);

        jLabel21.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText(":");
        jLabel21.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel21);
        jLabel21.setBounds(1110, 90, 30, 30);

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(580, 5, 20, 30);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("GRN Number");
        jLabel8.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 80, 120, 30);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Total");
        jLabel13.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel13);
        jLabel13.setBounds(590, 80, 120, 30);

        login_la_mini.setBackground(new java.awt.Color(255, 255, 255));
        login_la_mini.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        login_la_mini.setForeground(new java.awt.Color(0, 0, 0));
        login_la_mini.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_la_mini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_la_miniMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                login_la_miniMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                login_la_miniMouseExited(evt);
            }
        });
        getContentPane().add(login_la_mini);
        login_la_mini.setBounds(1295, 10, 30, 30);

        tx_grn_number.setBackground(new java.awt.Color(255, 255, 255));
        tx_grn_number.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tx_grn_number.setForeground(new java.awt.Color(0, 0, 0));
        tx_grn_number.setText("jTextField1");
        tx_grn_number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tx_grn_numberKeyPressed(evt);
            }
        });
        getContentPane().add(tx_grn_number);
        tx_grn_number.setBounds(190, 80, 320, 33);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Supplier Name");
        jLabel4.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 130, 130, 30);

        jLabel20.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Closing Date");
        jLabel20.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel20);
        jLabel20.setBounds(990, 90, 120, 30);

        login_la_cloce.setBackground(new java.awt.Color(255, 255, 255));
        login_la_cloce.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        login_la_cloce.setForeground(new java.awt.Color(0, 0, 0));
        login_la_cloce.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_la_cloce.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_la_cloceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                login_la_cloceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                login_la_cloceMouseExited(evt);
            }
        });
        getContentPane().add(login_la_cloce);
        login_la_cloce.setBounds(1330, 10, 30, 30);

        jLabel25.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText(":");
        jLabel25.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel25);
        jLabel25.setBounds(710, 130, 30, 30);

        jTable_grn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Grn ID", "Supplier", "Date", "Time", "Total", "Pay Roal", "Pay", "Blance", "Closing Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_grn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_grnMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_grn);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 410, 1310, 320);

        tx_gen_time.setBackground(new java.awt.Color(255, 255, 255));
        tx_gen_time.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tx_gen_time.setForeground(new java.awt.Color(0, 0, 0));
        tx_gen_time.setText("jTextField1");
        tx_gen_time.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tx_gen_timeKeyPressed(evt);
            }
        });
        getContentPane().add(tx_gen_time);
        tx_gen_time.setBounds(190, 230, 320, 33);

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator5);
        jSeparator5.setBounds(0, 320, 1370, 10);

        jLabel1.setBackground(new java.awt.Color(51, 204, 255));
        jLabel1.setFont(new java.awt.Font("Eras Bold ITC", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GRN LIST");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(760, 1, 330, 40);

        jComboBox_payroal.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox_payroal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jComboBox_payroal.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox_payroal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cash", "Check" }));
        jComboBox_payroal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox_payroalKeyPressed(evt);
            }
        });
        getContentPane().add(jComboBox_payroal);
        jComboBox_payroal.setBounds(730, 130, 180, 33);

        jLabel22.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Pay Roal");
        jLabel22.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel22);
        jLabel22.setBounds(590, 130, 120, 30);

        grn_la_listofgrnFrame_open.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        grn_la_listofgrnFrame_open.setForeground(new java.awt.Color(0, 0, 0));
        grn_la_listofgrnFrame_open.setText("grn item");
        grn_la_listofgrnFrame_open.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grn_la_listofgrnFrame_openMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                grn_la_listofgrnFrame_openMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                grn_la_listofgrnFrame_openMouseExited(evt);
            }
        });
        getContentPane().add(grn_la_listofgrnFrame_open);
        grn_la_listofgrnFrame_open.setBounds(1160, 330, 120, 40);

        agent_la_time.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        agent_la_time.setForeground(new java.awt.Color(255, 255, 255));
        agent_la_time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agent_la_time.setText("Invoice");
        agent_la_time.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(agent_la_time);
        agent_la_time.setBounds(150, 5, 130, 35);

        tx_gen_date.setBackground(new java.awt.Color(255, 255, 255));
        tx_gen_date.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tx_gen_date.setForeground(new java.awt.Color(0, 0, 0));
        tx_gen_date.setText("jTextField1");
        tx_gen_date.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tx_gen_dateKeyPressed(evt);
            }
        });
        getContentPane().add(tx_gen_date);
        tx_gen_date.setBounds(190, 180, 320, 33);

        agent_la_date.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        agent_la_date.setForeground(new java.awt.Color(255, 255, 255));
        agent_la_date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agent_la_date.setText("Invoice");
        agent_la_date.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(agent_la_date);
        agent_la_date.setBounds(10, 5, 130, 35);

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(140, 5, 20, 30);

        grn_la_print.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        grn_la_print.setForeground(new java.awt.Color(0, 0, 0));
        grn_la_print.setText("Print");
        grn_la_print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grn_la_printMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                grn_la_printMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                grn_la_printMouseExited(evt);
            }
        });
        getContentPane().add(grn_la_print);
        grn_la_print.setBounds(950, 330, 130, 60);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText(":");
        jLabel12.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel12);
        jLabel12.setBounds(710, 80, 30, 30);

        doctor_la_login_use_name.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        doctor_la_login_use_name.setForeground(new java.awt.Color(255, 255, 255));
        doctor_la_login_use_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        doctor_la_login_use_name.setText("Invoice");
        getContentPane().add(doctor_la_login_use_name);
        doctor_la_login_use_name.setBounds(330, 5, 260, 35);

        grn_la_new.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        grn_la_new.setForeground(new java.awt.Color(0, 0, 0));
        grn_la_new.setText("New");
        grn_la_new.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grn_la_newMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                grn_la_newMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                grn_la_newMouseExited(evt);
            }
        });
        getContentPane().add(grn_la_new);
        grn_la_new.setBounds(570, 330, 120, 40);

        grn_tx_barcode.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        grn_tx_barcode.setForeground(new java.awt.Color(255, 255, 255));
        grn_tx_barcode.setText("Date");
        grn_tx_barcode.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(grn_tx_barcode);
        grn_tx_barcode.setBounds(30, 180, 120, 30);

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(280, 5, 20, 30);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 43, 1370, 2);

        home_la_uesr_image.setText("userlogo");
        getContentPane().add(home_la_uesr_image);
        home_la_uesr_image.setBounds(290, 10, 30, 30);

        jLabel26.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Status");
        jLabel26.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel26);
        jLabel26.setBounds(990, 140, 120, 30);

        jLabel14.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText(":");
        jLabel14.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel14);
        jLabel14.setBounds(160, 230, 30, 30);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText(":");
        jLabel10.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel10);
        jLabel10.setBounds(1110, 140, 30, 30);

        grn_la_barcode.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        grn_la_barcode.setForeground(new java.awt.Color(255, 255, 255));
        grn_la_barcode.setText("Time");
        grn_la_barcode.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(grn_la_barcode);
        grn_la_barcode.setBounds(30, 230, 120, 30);

        tx_total.setBackground(new java.awt.Color(255, 255, 255));
        tx_total.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tx_total.setForeground(new java.awt.Color(0, 0, 0));
        tx_total.setText("jTextField1");
        tx_total.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tx_totalKeyPressed(evt);
            }
        });
        getContentPane().add(tx_total);
        tx_total.setBounds(730, 80, 180, 33);

        jLabel27.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Balance");
        jLabel27.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel27);
        jLabel27.setBounds(590, 230, 120, 30);

        jLabel28.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText(":");
        jLabel28.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel28);
        jLabel28.setBounds(710, 230, 30, 30);

        tx_balance.setBackground(new java.awt.Color(255, 255, 255));
        tx_balance.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tx_balance.setForeground(new java.awt.Color(0, 0, 0));
        tx_balance.setText("jTextField1");
        tx_balance.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tx_balanceKeyPressed(evt);
            }
        });
        getContentPane().add(tx_balance);
        tx_balance.setBounds(730, 230, 180, 33);

        jComboBox_status.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox_status.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jComboBox_status.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox_status.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Payed", "No", "Pending" }));
        jComboBox_status.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox_statusKeyPressed(evt);
            }
        });
        getContentPane().add(jComboBox_status);
        jComboBox_status.setBounds(1140, 140, 170, 33);

        supplier_la_search.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        supplier_la_search.setForeground(new java.awt.Color(0, 0, 0));
        supplier_la_search.setText("Search");
        supplier_la_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supplier_la_searchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                supplier_la_searchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                supplier_la_searchMouseExited(evt);
            }
        });
        getContentPane().add(supplier_la_search);
        supplier_la_search.setBounds(40, 330, 120, 40);

        supplier_la_update.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        supplier_la_update.setForeground(new java.awt.Color(0, 0, 0));
        supplier_la_update.setText("Update");
        supplier_la_update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supplier_la_updateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                supplier_la_updateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                supplier_la_updateMouseExited(evt);
            }
        });
        getContentPane().add(supplier_la_update);
        supplier_la_update.setBounds(220, 330, 120, 40);

        background.setBackground(new java.awt.Color(234, 232, 232));
        background.setForeground(new java.awt.Color(255, 255, 255));
        background.setText("jLabel1");
        getContentPane().add(background);
        background.setBounds(0, 0, 1380, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tx_payKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tx_payKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            u.grabFocusMethod(evt, tx_pay, tx_balance);
            tx_balance.setText(""+(Double.parseDouble(tx_total.getText())-Double.parseDouble(tx_pay.getText())));
        } else {
            txValidateKeyEvent(evt, tx_pay, "N", 10);
           
        }
    }//GEN-LAST:event_tx_payKeyPressed

    private void jDateChooser_cdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDateChooser_cdKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            u.grabFocusMethod(evt, jDateChooser_cd, jComboBox_status);
        }
    }//GEN-LAST:event_jDateChooser_cdKeyPressed

    private void agent_la_home_imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agent_la_home_imgMouseClicked
        int x = JOptionPane.showConfirmDialog(this, "Do you sure Go to The Home ?", "Change Interface", JOptionPane.YES_NO_OPTION);
        if (JOptionPane.YES_OPTION == x) {
            home.getCallPopup().setVisible(true);
            this.dispose();
        } else if (JOptionPane.NO_OPTION == x) {
            setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);

        }
    }//GEN-LAST:event_agent_la_home_imgMouseClicked

    private void agent_la_home_imgMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agent_la_home_imgMouseEntered
        u.imageMethod("/img/home_2_2.png", agent_la_home_img);
    }//GEN-LAST:event_agent_la_home_imgMouseEntered

    private void agent_la_home_imgMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agent_la_home_imgMouseExited
        u.imageMethod("/img/home_.png", agent_la_home_img);
    }//GEN-LAST:event_agent_la_home_imgMouseExited

    private void grn_la_enterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grn_la_enterMouseClicked
  u.imageMethod("/img/enter2.png", grn_la_enter );
        int x = JOptionPane.showConfirmDialog(this, "Do you sure add this GRN ?", "Conform The ADD Item ???", JOptionPane.YES_NO_OPTION);
        if (JOptionPane.YES_OPTION == x) {
            emterMouseClickMethod();
        } else if (JOptionPane.NO_OPTION == x) {
            setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
            tx_gen_date.grabFocus();
        }
    }//GEN-LAST:event_grn_la_enterMouseClicked

    private void grn_la_enterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grn_la_enterMouseEntered
        u.imageMethod("/img/enter2.png", grn_la_enter);
    }//GEN-LAST:event_grn_la_enterMouseEntered

    private void grn_la_enterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grn_la_enterMouseExited
        u.imageMethod("/img/enter.png", grn_la_enter);
    }//GEN-LAST:event_grn_la_enterMouseExited

    private void login_la_miniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_la_miniMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_login_la_miniMouseClicked

    private void login_la_miniMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_la_miniMouseEntered
        //    login_la_mini.setBackground(Color.gray);
        u.imageMethod("/img/mini2.png", login_la_mini);
    }//GEN-LAST:event_login_la_miniMouseEntered

    private void login_la_miniMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_la_miniMouseExited
        //    login_la_mini.setBackground(Color.white);
        u.imageMethod("/img/mini.png", login_la_mini);
    }//GEN-LAST:event_login_la_miniMouseExited

    private void tx_grn_numberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tx_grn_numberKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            u.grabFocusMethod(evt, tx_grn_number, jComboBox_Supplier_name);
            tx_gen_date.setText(agent_la_date.getText());
             tx_gen_time.setText(agent_la_time.getText());
        } else {
            txValidateKeyEvent(evt, tx_grn_number, "N", 10);
        }
    }//GEN-LAST:event_tx_grn_numberKeyPressed

    private void login_la_cloceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_la_cloceMouseClicked
        SystemClose();
    }//GEN-LAST:event_login_la_cloceMouseClicked

    private void login_la_cloceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_la_cloceMouseEntered
        //    login_la_cloce.setBackground(Color.red);
        u.imageMethod("/img/exti.png", login_la_cloce);
    }//GEN-LAST:event_login_la_cloceMouseEntered

    private void login_la_cloceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_la_cloceMouseExited
        //    login_la_cloce.setBackground(Color.white);
        u.imageMethod("/img/exti2.png", login_la_cloce);
    }//GEN-LAST:event_login_la_cloceMouseExited

    private void tx_gen_timeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tx_gen_timeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_gen_timeKeyPressed

    private void jComboBox_payroalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox_payroalKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            u.grabFocusMethod(evt, jComboBox_payroal, tx_pay);
        }
    }//GEN-LAST:event_jComboBox_payroalKeyPressed

    private void grn_la_listofgrnFrame_openMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grn_la_listofgrnFrame_openMouseClicked
        grn.getCallPopup(this,st).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_grn_la_listofgrnFrame_openMouseClicked

    private void grn_la_listofgrnFrame_openMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grn_la_listofgrnFrame_openMouseEntered
        //  u.imageMethod("/img/userFrame2.png", agent_la_userFrame_open );
        u.imageMethod("/img/grnitem2.png", grn_la_listofgrnFrame_open);
    }//GEN-LAST:event_grn_la_listofgrnFrame_openMouseEntered

    private void grn_la_listofgrnFrame_openMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grn_la_listofgrnFrame_openMouseExited
        // u.imageMethod("/img/userFrame.png", agent_la_userFrame_open );
        u.imageMethod("/img/grnitem1.png", grn_la_listofgrnFrame_open);
    }//GEN-LAST:event_grn_la_listofgrnFrame_openMouseExited

    private void tx_gen_dateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tx_gen_dateKeyPressed
        
    }//GEN-LAST:event_tx_gen_dateKeyPressed

    private void grn_la_printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grn_la_printMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_grn_la_printMouseClicked

    private void grn_la_printMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grn_la_printMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_grn_la_printMouseEntered

    private void grn_la_printMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grn_la_printMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_grn_la_printMouseExited

    private void grn_la_newMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grn_la_newMouseClicked
        u.imageMethod("/img/newB2.png", grn_la_new);
        cleareFields();
    }//GEN-LAST:event_grn_la_newMouseClicked

    private void grn_la_newMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grn_la_newMouseEntered
        u.imageMethod("/img/newB2.png", grn_la_new);
    }//GEN-LAST:event_grn_la_newMouseEntered

    private void grn_la_newMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grn_la_newMouseExited
        u.imageMethod("/img/newB.png", grn_la_new);
    }//GEN-LAST:event_grn_la_newMouseExited

    private void tx_totalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tx_totalKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            u.grabFocusMethod(evt, tx_total, jComboBox_payroal);
        } else {
            txValidateKeyEvent(evt, tx_total, "N", 10);
        }
    }//GEN-LAST:event_tx_totalKeyPressed

    private void jComboBox_Supplier_nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox_Supplier_nameKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            u.grabFocusMethod(evt, jComboBox_Supplier_name, tx_total);
        }
    }//GEN-LAST:event_jComboBox_Supplier_nameKeyPressed

    private void tx_balanceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tx_balanceKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
           // u.grabFocusMethod(evt, tx_balance, jDateChooser_cd);
            tx_balance.grabFocus();
        } else {
            txValidateKeyEvent(evt, tx_balance, "N", 10);
        }
    }//GEN-LAST:event_tx_balanceKeyPressed

    private void jComboBox_statusKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox_statusKeyPressed
       if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            u.grabFocusMethod(evt, jComboBox_status, grn_la_enter);
        }
    }//GEN-LAST:event_jComboBox_statusKeyPressed

    private void supplier_la_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplier_la_searchMouseClicked
        u.imageMethod("/img/search2.png", supplier_la_search );
        if (idsearch != 0) {
            searchgrn();
        } else {
            JOptionPane.showMessageDialog(null, "Error Not Selected The GRN  !!! \n searchGRN() \n" , "Error Massage", JOptionPane.ERROR_MESSAGE);
            tx_grn_number.grabFocus();
        }
    }//GEN-LAST:event_supplier_la_searchMouseClicked

    private void supplier_la_searchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplier_la_searchMouseEntered
        u.imageMethod("/img/search2.png", supplier_la_search );
    }//GEN-LAST:event_supplier_la_searchMouseEntered

    private void supplier_la_searchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplier_la_searchMouseExited
        u.imageMethod("/img/search.png", supplier_la_search );
    }//GEN-LAST:event_supplier_la_searchMouseExited

    private void supplier_la_updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplier_la_updateMouseClicked
u.imageMethod("/img/update2.png", supplier_la_update );
        if (idsearch == 0) {
            JOptionPane.showMessageDialog(this, "Please Select the GRN", "Not Selected", JOptionPane.OK_OPTION);
        } else {
            updateGRN();
        }
    }//GEN-LAST:event_supplier_la_updateMouseClicked

    private void supplier_la_updateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplier_la_updateMouseEntered
        u.imageMethod("/img/update2.png", supplier_la_update );
    }//GEN-LAST:event_supplier_la_updateMouseEntered

    private void supplier_la_updateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplier_la_updateMouseExited
        u.imageMethod("/img/update.png", supplier_la_update );
    }//GEN-LAST:event_supplier_la_updateMouseExited

    private void jTable_grnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_grnMouseClicked
        DefaultTableModel defTabMod = (DefaultTableModel) jTable_grn.getModel();
        grn_la_new.setVisible(true);
        grn_la_enter.setVisible(false);
        idsearch = Integer.parseInt(defTabMod.getValueAt(jTable_grn.getSelectedRow(), 0).toString());
        tx_grn_number.setText(defTabMod.getValueAt(jTable_grn.getSelectedRow(), 0).toString());
        jComboBox_Supplier_name.setSelectedItem(defTabMod.getValueAt(jTable_grn.getSelectedRow(), 1).toString());
        tx_gen_date.setText(defTabMod.getValueAt(jTable_grn.getSelectedRow(), 2).toString());
        tx_gen_time.setText(defTabMod.getValueAt(jTable_grn.getSelectedRow(), 3).toString());
        tx_total.setText(defTabMod.getValueAt(jTable_grn.getSelectedRow(), 4).toString());
        jComboBox_payroal.setSelectedItem(defTabMod.getValueAt(jTable_grn.getSelectedRow(), 5).toString());
        tx_pay.setText(defTabMod.getValueAt(jTable_grn.getSelectedRow(), 6).toString());
        tx_balance.setText(defTabMod.getValueAt(jTable_grn.getSelectedRow(), 7).toString());
       
     try {
       Date  date = new SimpleDateFormat("yyyy-MM-dd").parse((String)defTabMod.getValueAt(jTable_grn.getSelectedRow(), 8).toString());
        jDateChooser_cd.setDate(date);
     } catch (ParseException ex) {
          systemLogger.initLogger(grnlist.class).error(" tablemouse Clock ParseException Error",ex);
          jDateChooser_cd.setDate(null);
     }
       
        
        jComboBox_status.setSelectedItem(defTabMod.getValueAt(jTable_grn.getSelectedRow(), 9).toString());
    }//GEN-LAST:event_jTable_grnMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
       tx_gen_date.setText(agent_la_date.getText());
        tx_gen_time.setText(agent_la_time.getText());
    }//GEN-LAST:event_formMouseClicked

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
       tx_gen_date.setText(agent_la_date.getText());
        tx_gen_time.setText(agent_la_time.getText());
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(grnlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(grnlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(grnlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(grnlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new grnlist().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agent_la_date;
    private javax.swing.JLabel agent_la_home_img;
    private javax.swing.JLabel agent_la_time;
    private javax.swing.JLabel background;
    private javax.swing.JLabel doctor_la_login_use_name;
    private javax.swing.JLabel grn_la_barcode;
    private javax.swing.JLabel grn_la_enter;
    private javax.swing.JLabel grn_la_listofgrnFrame_open;
    private javax.swing.JLabel grn_la_new;
    private javax.swing.JLabel grn_la_print;
    private javax.swing.JLabel grn_tx_barcode;
    private javax.swing.JLabel home_la_uesr_image;
    private javax.swing.JComboBox jComboBox_Supplier_name;
    private javax.swing.JComboBox jComboBox_payroal;
    private javax.swing.JComboBox jComboBox_status;
    private com.toedter.calendar.JDateChooser jDateChooser_cd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable jTable_grn;
    private javax.swing.JLabel login_la_cloce;
    private javax.swing.JLabel login_la_mini;
    private javax.swing.JLabel supplier_la_search;
    private javax.swing.JLabel supplier_la_update;
    private javax.swing.JTextField tx_balance;
    private javax.swing.JTextField tx_gen_date;
    private javax.swing.JTextField tx_gen_time;
    private javax.swing.JTextField tx_grn_number;
    private javax.swing.JTextField tx_pay;
    private javax.swing.JTextField tx_total;
    // End of variables declaration//GEN-END:variables
//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\ 
    /* *** >>> Date ------------>>> 
     * *** >>> What ------------>>> Singltan class 
     * *** >>> Why ------------->>> ek object ekk hdnn
     * *** >>> Parameters ------>>>
     * *** >>> Status ---------->>>
     */
//>>>>>>>>> Get Instance <<<<<<<<<<<  
    private static final grnlist doctor = new grnlist();

    public static grnlist getCallPopup(stock s) {
        st = s;
        return doctor;
    }
//>>>>>>>>> Get Instance <<<<<<<<<<<         

//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\ 
    //---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\ 
    /* *** >>> Date ------------>>> 
     * *** >>> What ------------>>>  
     * *** >>> Why ------------->>>
     * *** >>> Parameters ------>>>
     * *** >>> Status ---------->>>
     */
//>>>>>>>>> cleareFields <<<<<<<<<<<      
    private void cleareFields() {
        tx_grn_number.setText(null);
         tx_grn_number.grabFocus();
        jComboBox_Supplier_name.setSelectedIndex(0);
        tx_gen_date.setText(null);
        tx_gen_time.setText(null);
        tx_total.setText(null);
        jComboBox_payroal.setSelectedIndex(0);
        tx_pay.setText(null);
        tx_balance.setText(null);
        jDateChooser_cd.setDate(null);
        jComboBox_status.setSelectedIndex(0);
        
        idsearch = 0;
        
        grn_la_enter.setVisible(true);
        grn_la_new.setVisible(false);
        grn_la_print.setVisible(false);
        
        tx_gen_date.setText(agent_la_date.getText());
        tx_gen_time.setText(agent_la_time.getText());
        tx_gen_date.setEditable(false);
        tx_gen_time.setEditable(false);
        jTable_grn.removeAll();
        selectAllGRN();
        SearchAndListJcomboboxSupplier();
    }
//>>>>>>>>> cleareFields <<<<<<<<<<<         

//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\ 

//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\ 
    /* *** >>> Date ------------>>> mon 6 September
     * *** >>> What ------------>>> txValidateKeyEvent()
     * *** >>> Why ------------->>>
     * *** >>> Parameters ------>>> KeyEvent evt, JTextField txName, String txType, int lenthNeedFeld
     * *** >>> Status ---------->>>
     */
    //>>>>>>>>> txValidateKeyEvent cloce <<<<<<<<<<<      
    private void txValidateKeyEvent(KeyEvent evt, JTextField txName, String txType, int lenthNeedFeld) {
        int dot = 0;
        int iNumber = evt.getKeyCode();
        if (txName.getText().length() <= lenthNeedFeld) {
            
            if (txType.equals("N")) {

                if ((iNumber >= 96 & iNumber <= 105) | (iNumber >= 48 & iNumber <= 57) | (iNumber == 8)) {
                    txName.setEditable(true);
                } else {
                    txName.setEditable(false);
                }

            }
            if (txType.equals("PRICE")) {

                if ((iNumber >= 96 & iNumber <= 105) | (iNumber >= 48 & iNumber <= 57) | (iNumber == 8) | (iNumber == 110)) {
                    if (iNumber == 110) {
                        dot = dot + 1;
                    }
                    if (dot == 2) {
                        JOptionPane.showMessageDialog(null, "Error , You try 2 desimal simbles!!! \n ", "Error Massage", JOptionPane.ERROR_MESSAGE);
                        dot = 1;
//                            if (txName.getText().contains(".") ) {
//                                txName.setText(txName.getText());
//                            }
                    } else {
                        txName.setEditable(true);
                    }

                } else {
                    txName.setEditable(false);
                }

            }
            

        } else if ((iNumber == 8)) {
            txName.setEditable(true);
        } else {
            txName.setEditable(false);
        }

    }
    //>>>>>>>>> txValidateKeyEvent cloce <<<<<<<<<<<       

//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\   
    //---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\ 
    /* *** >>> Date ------------>>> mon 6 September
     * *** >>> What ------------>>> SystemClose()
     * *** >>> Why ------------->>>
     * *** >>> Parameters ------>>> no
     * *** >>> Status ---------->>>
     */
    //>>>>>>>>> System cloce <<<<<<<<<<<   
    void SystemClose() {
        int x = JOptionPane.showConfirmDialog(this, "Do you sure close the System ?", "Exit System", JOptionPane.YES_NO_OPTION);
        if (JOptionPane.YES_OPTION == x) {
            // setDefaultCloseOperation(EXIT_ON_CLOSE);
          st.setVisible(true);
           this.dispose();
        } else if (JOptionPane.NO_OPTION == x) {
            setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
            login_la_cloce.setBackground(new Color(153, 204, 255));
        }
    }
    //>>>>>>>>> System cloce <<<<<<<<<<<       

//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\  
//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\ 
    /* *** >>> Date ------------>>> 
     * *** >>> What ------------>>>  
     * *** >>> Why ------------->>> 
     * *** >>> Parameters ------>>>
     * *** >>> Status ---------->>>
     */
//>>>>>>>>> emterMouseClickMethod <<<<<<<<<<< 
    private void emterMouseClickMethod() {
        if (tx_grn_number.getText().trim().isEmpty()) {
            tx_grn_number.grabFocus();
        } else if (tx_total.getText().trim().isEmpty()) {
            tx_total.grabFocus();
        }else if (tx_pay.getText().trim().isEmpty()) {
            tx_pay.grabFocus();
        } else if (tx_balance.getText().trim().isEmpty()) {
            tx_balance.grabFocus();
        }else if (!(tx_grn_number.getText().trim().isEmpty() & tx_total.getText().trim().isEmpty()
                & tx_pay.getText().trim().isEmpty() & tx_balance.getText().trim().isEmpty())) {
            addJTable();
        }
    }
    //>>>>>>>>> emterMouseClickMethod <<<<<<<<<<<         
//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\     //---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\ 
    /* *** >>> Date ------------>>> 
     * *** >>> What ------------>>>  
     * *** >>> Why ------------->>> 
     * *** >>> Parameters ------>>>
     * *** >>> Status ---------->>>
     */
//>>>>>>>>> updateGRN <<<<<<<<<<<     
    private void updateGRN() {
        try {
            DBClass.putData("update grn set pay='"+Double.parseDouble(tx_pay.getText())+"', balance='" + Double.parseDouble(tx_balance.getText()) + "',status='" + jComboBox_status.getSelectedItem().toString() + "'  where  idgrn='"+idsearch+"' ");
            JOptionPane.showMessageDialog(this, "Update Successful", "Updated", JOptionPane.OK_OPTION);
            cleareFields();
            selectAllGRN();
        } catch (Exception e) {
            systemLogger.initLogger(grnlist.class).error(" updateGRN() Error",e);
JOptionPane.showMessageDialog(null, "Error GRNTableUpdate !!! \n "+e, "Error Massage", JOptionPane.ERROR_MESSAGE);
tx_grn_number.grabFocus();
        }
    }
    //>>>>>>>>> updateGRN <<<<<<<<<<<         

//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\   

  
//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\ 
    /* *** >>> Date ------------>>> 
     * *** >>> What ------------>>> 
     * *** >>> Why ------------->>> 
     * *** >>> Parameters ------>>>
     * *** >>> Status ---------->>>
     */
//>>>>>>>>> addJTable <<<<<<<<<<<      
    private void addJTable() {
        try {
            int idsupplier =0;
            DBClass.getData("select idsupplier from supplier where comname='" + jComboBox_Supplier_name.getSelectedItem().toString() + "' order by idsupplier");
            while(DBClass.r.next()){ idsupplier = DBClass.r.getInt("idsupplier");}
            SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            String  d1 = df.format(jDateChooser_cd.getDate());
            
            DBClass.putData("insert into grn(idgrn,idsupplier,date,time,total,payroal,pay,balance,status,closingdate) values("
                    + "'" + Integer.parseInt(tx_grn_number.getText()) + "' , '" + idsupplier + "','" + tx_gen_date.getText() + "' "
                    + " ,'" + tx_gen_time.getText() +"','" + Double.parseDouble(tx_total.getText()) + "','"+jComboBox_payroal.getSelectedItem().toString()+"' "
                    + ",'"+ Double.parseDouble(tx_pay.getText())+"','" + Double.parseDouble(tx_balance.getText())
                    + "','" + jComboBox_status.getSelectedItem().toString() + "','" + d1 + "' )");

            
            cleareFields();
            selectAllGRN();
        } catch (Exception ex) {
             systemLogger.initLogger(grnlist.class).error(" addJTable() Error",ex);
            JOptionPane.showMessageDialog(null, "Error GrnListTableInsert !!! \n ", "Error Massage", JOptionPane.ERROR_MESSAGE);
            tx_grn_number.grabFocus();
        }
    }
//>>>>>>>>> addJTable <<<<<<<<<<<         

//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\ 
    /* *** >>> Date ------------>>> 
     * *** >>> What ------------>>>  
     * *** >>> Why ------------->>> 
     * *** >>> Parameters ------>>>
     * *** >>> Status ---------->>>
     */
//>>>>>>>>> selectAllGRN <<<<<<<<<<<      
    private void selectAllGRN() {
        try {
            DefaultTableModel defTabMod = (DefaultTableModel) jTable_grn.getModel();
            defTabMod.getDataVector().removeAllElements();
            //  ResultSet rs = DBClass.getData("select * from supplier where idsupplier  ='" + tx_doctor_id.getText() + "' order by iddoctor");
           // DBClass.getData("select * from grn where status='NO'|'Pending' order by idgrn");
            DBClass.getData("select g.idgrn,g.date,g.time,g.total,g.payroal,g.pay,g.balance,g.status,g.closingdate,s.comname from grn g inner join supplier s on g.idsupplier=s.idsupplier where g.status='NO'|'Pending' order by idgrn");
            if (DBClass.r.isBeforeFirst() == true) {
                while (DBClass.r.next()) {
                    Vector v = new Vector();
                    v.add(DBClass.r.getString("g.idgrn"));
                       v.add(DBClass.r.getString("s.comname"));
                    v.add(DBClass.r.getString("g.date"));
                    v.add(DBClass.r.getString("g.time"));
                    v.add(DBClass.r.getString("g.total"));
                    v.add(DBClass.r.getString("g.payroal"));
                    v.add(DBClass.r.getString("g.pay"));
                    v.add(DBClass.r.getString("g.balance"));
                    v.add(DBClass.r.getString("g.closingdate"));
                    v.add(DBClass.r.getString("g.status"));
                    
                    defTabMod.addRow(v);
                    
                }
            }

        } catch (Exception ex) {
             systemLogger.initLogger(grnlist.class).error(" selectAllGRN() Error",ex);
            JOptionPane.showMessageDialog(null, "Error SelectselectAllGRN !!! \n selectAllGRN() \n", "Error Massage", JOptionPane.ERROR_MESSAGE);
            tx_grn_number.grabFocus();
        }
    }
    //>>>>>>>>> selectAllGRN <<<<<<<<<<<         

//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\ 
    /* *** >>> Date ------------>>> 
     * *** >>> What ------------>>>  
     * *** >>> Why ------------->>> 
     * *** >>> Parameters ------>>>
     * *** >>> Status ---------->>>
     */
//>>>>>>>>> searchgrn <<<<<<<<<<<      
    private void searchgrn() {
        try {
             DefaultTableModel defTabMod = (DefaultTableModel) jTable_grn.getModel();
             defTabMod.getDataVector().removeAllElements();
          //  ResultSet rs = DBClass.getData("select * from supplier where idsupplier  ='" + tx_doctor_id.getText() + "' order by iddoctor");
            DBClass.getData("select * from grn where idgrn like '" + tx_grn_number.getText() + "%' order by idgrn");
           
            if (DBClass.r.isBeforeFirst() == true) {
                while (DBClass.r.next()) {
 Vector v = new Vector();
                    v.add(DBClass.r.getString("idgrn"));
                    DBClass.getData("select comname from supplier where idsupplier= '" + DBClass.r.getString("idsupplier") + "'");
                    if (DBClass.r.isBeforeFirst() == true) {
                        v.add(DBClass.r.getString("comname"));
                    }
                    v.add(DBClass.r.getString("date"));
                    v.add(DBClass.r.getString("time"));
                    v.add(DBClass.r.getString("total"));
                    v.add(DBClass.r.getString("payroal"));
                    v.add(DBClass.r.getString("balance"));
                    v.add(DBClass.r.getString("status"));
                    v.add(DBClass.r.getString("closingdate"));
                    defTabMod.addRow(v);
                    
                    grn_la_enter.setVisible(false);
                    grn_la_new.setVisible(true);
                }
            }
            
        } catch (Exception ex) {
            systemLogger.initLogger(grnlist.class).error(" searchgrn() Error",ex);
 JOptionPane.showMessageDialog(null, "Error GRNTableSearch !!! \n searchgrn() \n", "Error Massage", JOptionPane.ERROR_MESSAGE);
 tx_grn_number.grabFocus();
     }
    }
    //>>>>>>>>> searchgrn <<<<<<<<<<<         

//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\ 
    /* *** >>> Date ------------>>> 
     * *** >>> What ------------>>>  
     * *** >>> Why ------------->>> 
     * *** >>> Parameters ------>>>
     * *** >>> Status ---------->>>
     */
//>>>>>>>>> SearchAndListJcomboboxSupplier <<<<<<<<<<<     
    private void SearchAndListJcomboboxSupplier() {
        try {
             jComboBox_Supplier_name.removeAllItems();
            DBClass.getData("select comname from supplier where status='1' order by idsupplier");
            
            if (DBClass.r.isBeforeFirst() == true) {
                while (DBClass.r.next()) {
                    jComboBox_Supplier_name.addItem(DBClass.r.getString("comname"));
                 }
            }
        } catch (Exception e) {
              systemLogger.initLogger(item.class).error("SearchAndListJcomboboxSupplier()  Error",e);
            JOptionPane.showMessageDialog(null, "Error SupplierTablesearch !!! \n SearchAndListJcomboboxSupplier() \n", "Error Massage", JOptionPane.ERROR_MESSAGE);
            tx_grn_number.grabFocus();
        }
    }
    //>>>>>>>>> SearchAndListJcomboboxSupplier <<<<<<<<<<<         

//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\    

}
