/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import java.util.Properties;
import java.util.Vector;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;

/**
 *
 * @author CHETHANA
 */
public class protoal extends javax.swing.JFrame {
 UniversalMethod u = new UniversalMethod();
 public static String d1;
  public static String d2;
  public static String t1;
    /**
     * Creates new form protoal
     */
    public protoal() {
        initComponents();
         systemLogger.initLogger(protoal.class).info("Open Protoal  Frame");
          UniversalMethod.TimeMethod(agent_la_date, agent_la_time);
         u.imageMethod(background, home_la_uesr_image, doctor_la_login_use_name, agent_la_home_img, login_la_mini, login_la_cloce);
       cleareFields();
       u.imageMethod("/img/print11.png", la_print);
        u.imageMethod("/img/newB.png", grn_la_new);
         u.imageMethod("/img/search.png", supplier_la_search );
   doctor_la_login_use_name.setText(u.getLogUser());
   agent_la_home_img.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agent_la_home_img = new javax.swing.JLabel();
        login_la_cloce = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_d_a = new javax.swing.JTable();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        supplier_la_search = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        agent_la_time = new javax.swing.JLabel();
        doctor_la_login_use_name = new javax.swing.JLabel();
        grn_la_new = new javax.swing.JLabel();
        home_la_uesr_image = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        la_netT = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser_d1 = new com.toedter.calendar.JDateChooser();
        login_la_mini = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        la_print = new javax.swing.JLabel();
        agent_la_date = new javax.swing.JLabel();
        la_nin = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jDateChooser_d2 = new com.toedter.calendar.JDateChooser();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1376, 768));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1376, 768));
        getContentPane().setLayout(null);

        agent_la_home_img.setText("jLabel1");
        agent_la_home_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agent_la_home_imgMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                agent_la_home_imgMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                agent_la_home_imgMouseExited(evt);
            }
        });
        getContentPane().add(agent_la_home_img);
        agent_la_home_img.setBounds(600, 5, 80, 30);

        login_la_cloce.setBackground(new java.awt.Color(255, 255, 255));
        login_la_cloce.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        login_la_cloce.setForeground(new java.awt.Color(0, 0, 0));
        login_la_cloce.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_la_cloce.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_la_cloceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                login_la_cloceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                login_la_cloceMouseExited(evt);
            }
        });
        getContentPane().add(login_la_cloce);
        login_la_cloce.setBounds(1330, 10, 30, 30);

        jTable_d_a.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rx ID", "Date", "Time", "Total", "Discount", "Net Total", "Shippingcost", "Full Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_d_a);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 130, 1110, 610);

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(140, 5, 20, 30);

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(280, 5, 20, 30);

        supplier_la_search.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        supplier_la_search.setForeground(new java.awt.Color(0, 0, 0));
        supplier_la_search.setText("Search");
        supplier_la_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supplier_la_searchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                supplier_la_searchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                supplier_la_searchMouseExited(evt);
            }
        });
        getContentPane().add(supplier_la_search);
        supplier_la_search.setBounds(930, 80, 120, 40);

        jLabel1.setBackground(new java.awt.Color(51, 204, 255));
        jLabel1.setFont(new java.awt.Font("Eras Bold ITC", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Product Amount");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(760, 1, 330, 40);

        agent_la_time.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        agent_la_time.setForeground(new java.awt.Color(255, 255, 255));
        agent_la_time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agent_la_time.setText("Invoice");
        agent_la_time.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(agent_la_time);
        agent_la_time.setBounds(150, 5, 130, 35);

        doctor_la_login_use_name.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        doctor_la_login_use_name.setForeground(new java.awt.Color(255, 255, 255));
        doctor_la_login_use_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        doctor_la_login_use_name.setText("Invoice");
        getContentPane().add(doctor_la_login_use_name);
        doctor_la_login_use_name.setBounds(330, 5, 260, 35);

        grn_la_new.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        grn_la_new.setForeground(new java.awt.Color(0, 0, 0));
        grn_la_new.setText("New");
        grn_la_new.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grn_la_newMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                grn_la_newMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                grn_la_newMouseExited(evt);
            }
        });
        getContentPane().add(grn_la_new);
        grn_la_new.setBounds(1130, 80, 120, 40);

        home_la_uesr_image.setText("userlogo");
        getContentPane().add(home_la_uesr_image);
        home_la_uesr_image.setBounds(290, 10, 30, 30);

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("To");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(440, 80, 80, 20);

        la_netT.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        la_netT.setForeground(new java.awt.Color(204, 0, 51));
        getContentPane().add(la_netT);
        la_netT.setBounds(1190, 320, 150, 30);

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Form");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 80, 80, 20);
        getContentPane().add(jDateChooser_d1);
        jDateChooser_d1.setBounds(150, 80, 220, 29);

        login_la_mini.setBackground(new java.awt.Color(255, 255, 255));
        login_la_mini.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        login_la_mini.setForeground(new java.awt.Color(0, 0, 0));
        login_la_mini.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_la_mini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_la_miniMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                login_la_miniMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                login_la_miniMouseExited(evt);
            }
        });
        getContentPane().add(login_la_mini);
        login_la_mini.setBounds(1295, 10, 30, 30);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Number  OF Invoices");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(1190, 220, 150, 20);

        la_print.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        la_print.setForeground(new java.awt.Color(0, 0, 0));
        la_print.setText("Print");
        la_print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                la_printMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                la_printMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                la_printMouseExited(evt);
            }
        });
        la_print.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                la_printKeyPressed(evt);
            }
        });
        getContentPane().add(la_print);
        la_print.setBounds(1170, 640, 140, 80);

        agent_la_date.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        agent_la_date.setForeground(new java.awt.Color(255, 255, 255));
        agent_la_date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agent_la_date.setText("Invoice");
        agent_la_date.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(agent_la_date);
        agent_la_date.setBounds(10, 5, 130, 35);

        la_nin.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        la_nin.setForeground(new java.awt.Color(204, 0, 51));
        getContentPane().add(la_nin);
        la_nin.setBounds(1190, 240, 150, 30);

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator5);
        jSeparator5.setBounds(0, 40, 1370, 10);
        getContentPane().add(jDateChooser_d2);
        jDateChooser_d2.setBounds(510, 80, 220, 29);

        jSeparator9.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator9.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator9);
        jSeparator9.setBounds(580, 5, 20, 30);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Net Total Amount");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(1190, 300, 150, 20);

        background.setBackground(new java.awt.Color(234, 232, 232));
        background.setForeground(new java.awt.Color(255, 255, 255));
        background.setText("jLabel1");
        getContentPane().add(background);
        background.setBounds(0, 0, 1380, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agent_la_home_imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agent_la_home_imgMouseClicked
        u.imageMethod("/img/homeB1.png", agent_la_home_img);
        int x = JOptionPane.showConfirmDialog(this, "Do you sure Go to The Home ?", "Change Interface", JOptionPane.YES_NO_OPTION);
        if (JOptionPane.YES_OPTION == x) {
            home.getCallPopup().setVisible(true);
            this.dispose();
        } else if (JOptionPane.NO_OPTION == x) {
            setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);

        }
    }//GEN-LAST:event_agent_la_home_imgMouseClicked

    private void agent_la_home_imgMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agent_la_home_imgMouseEntered
        u.imageMethod("/img/homeB2.png", agent_la_home_img);
    }//GEN-LAST:event_agent_la_home_imgMouseEntered

    private void agent_la_home_imgMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agent_la_home_imgMouseExited
        u.imageMethod("/img/homeB1.png", agent_la_home_img);
    }//GEN-LAST:event_agent_la_home_imgMouseExited

    private void login_la_cloceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_la_cloceMouseClicked
        SystemClose();
    }//GEN-LAST:event_login_la_cloceMouseClicked

    private void login_la_cloceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_la_cloceMouseEntered
        //    login_la_cloce.setBackground(Color.red);
        u.imageMethod("/img/exti.png", login_la_cloce);
    }//GEN-LAST:event_login_la_cloceMouseEntered

    private void login_la_cloceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_la_cloceMouseExited
        //    login_la_cloce.setBackground(Color.white);
        u.imageMethod("/img/exti2.png", login_la_cloce);
    }//GEN-LAST:event_login_la_cloceMouseExited

    private void supplier_la_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplier_la_searchMouseClicked
        u.imageMethod("/img/search2.png", supplier_la_search );
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        d1 = df.format(jDateChooser_d1.getDate());
        d2 = df.format(jDateChooser_d2.getDate());
        search(d1,d2);
    }//GEN-LAST:event_supplier_la_searchMouseClicked

    private void supplier_la_searchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplier_la_searchMouseEntered
        u.imageMethod("/img/search2.png", supplier_la_search );
    }//GEN-LAST:event_supplier_la_searchMouseEntered

    private void supplier_la_searchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplier_la_searchMouseExited
        u.imageMethod("/img/search.png", supplier_la_search );
    }//GEN-LAST:event_supplier_la_searchMouseExited

    private void grn_la_newMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grn_la_newMouseClicked
        u.imageMethod("/img/newB2.png", grn_la_new);
        cleareFields();
    }//GEN-LAST:event_grn_la_newMouseClicked

    private void grn_la_newMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grn_la_newMouseEntered
        u.imageMethod("/img/newB2.png", grn_la_new);
    }//GEN-LAST:event_grn_la_newMouseEntered

    private void grn_la_newMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grn_la_newMouseExited
        u.imageMethod("/img/newB.png", grn_la_new);
    }//GEN-LAST:event_grn_la_newMouseExited

    private void login_la_miniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_la_miniMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_login_la_miniMouseClicked

    private void login_la_miniMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_la_miniMouseEntered
        //    login_la_mini.setBackground(Color.gray);
        u.imageMethod("/img/mini2.png", login_la_mini);
    }//GEN-LAST:event_login_la_miniMouseEntered

    private void login_la_miniMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_la_miniMouseExited
        //    login_la_mini.setBackground(Color.white);
        u.imageMethod("/img/mini.png", login_la_mini);
    }//GEN-LAST:event_login_la_miniMouseExited

    private void la_printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_la_printMouseClicked
        u.imageMethod("/img/print11.png", la_print);
        t1= agent_la_time.getText().replace(":","-");
        printInvoice();
        cleareFields();
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_la_printMouseClicked

    private void la_printMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_la_printMouseEntered
        u.imageMethod("/img/print22.png", la_print);
    }//GEN-LAST:event_la_printMouseEntered

    private void la_printMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_la_printMouseExited
        u.imageMethod("/img/print11.png", la_print);
    }//GEN-LAST:event_la_printMouseExited

    private void la_printKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_la_printKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            u.imageMethod("/img/print11.png", la_print);
            t1= agent_la_time.getText().replace(":","-");
            printInvoice();
            cleareFields();
            this.setState(JFrame.ICONIFIED);

        }
    }//GEN-LAST:event_la_printKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(protoal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(protoal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(protoal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(protoal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new protoal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agent_la_date;
    private javax.swing.JLabel agent_la_home_img;
    private javax.swing.JLabel agent_la_time;
    private javax.swing.JLabel background;
    private javax.swing.JLabel doctor_la_login_use_name;
    private javax.swing.JLabel grn_la_new;
    private javax.swing.JLabel home_la_uesr_image;
    private com.toedter.calendar.JDateChooser jDateChooser_d1;
    private com.toedter.calendar.JDateChooser jDateChooser_d2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable_d_a;
    private javax.swing.JLabel la_netT;
    private javax.swing.JLabel la_nin;
    private javax.swing.JLabel la_print;
    private javax.swing.JLabel login_la_cloce;
    private javax.swing.JLabel login_la_mini;
    private javax.swing.JLabel supplier_la_search;
    // End of variables declaration//GEN-END:variables

            //---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\ 
    /* *** >>> Date ------------>>> 
     * *** >>> What ------------>>>  
     * *** >>> Why ------------->>>
     * *** >>> Parameters ------>>>
     * *** >>> Status ---------->>>
     */
//>>>>>>>>> cleareFields <<<<<<<<<<<      
    private void cleareFields() {
        DefaultTableModel defTabMod = (DefaultTableModel) jTable_d_a.getModel();
            defTabMod.getDataVector().removeAllElements();
            jDateChooser_d1.setToolTipText(null);
             jDateChooser_d2.setToolTipText(null);
             d1="";
             d2="";
              la_netT.setText(null);
                la_nin.setText(null);
                t1="";
    }
//>>>>>>>>> cleareFields <<<<<<<<<<<         

//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\ 
  //---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\ 
    /* *** >>> Date ------------>>> 
     * *** >>> What ------------>>>  
     * *** >>> Why ------------->>>
     * *** >>> Parameters ------>>>
     * *** >>> Status ---------->>>
     */
//>>>>>>>>> search <<<<<<<<<<<      
    private void search(String d1 , String d2) {
        DefaultTableModel defTabMod = (DefaultTableModel) jTable_d_a.getModel();
        defTabMod.getDataVector().removeAllElements();
       try{
           if(d1.equals("")||d2.equals("")){
            
        }else{
        ResultSet rs =DBClass.getData("select idinvoice,date,time,total,dsicount,nettotal,shippingcost,fullamount "
                +"from invoice  where date between '"+d1+"' and '"+d2+"'  ");
     
           while (rs.next()) {
                Vector v = new Vector();
                    v.add(rs.getString("idinvoice"));
                    v.add(rs.getString("date"));
                    v.add(rs.getString("time"));
                    v.add(rs.getString("total"));
                    v.add(rs.getString("dsicount"));
                    v.add(rs.getString("nettotal"));
                    v.add(rs.getString("shippingcost"));
                    v.add(rs.getString("fullamount"));
                    defTabMod.addRow(v);
                }
           netToatl();
            }
        
       }catch(Exception e){
           systemLogger.initLogger(protoal.class).error("search()  Error",e);
           JOptionPane.showMessageDialog(null, "Error Not Selected Amount Date  !!! \n "+e+" search() \n" , "Error Massage", JOptionPane.ERROR_MESSAGE); 
       }
    }
//>>>>>>>>> search <<<<<<<<<<<         

//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\ 
    /* *** >>> Date ------------>>> mon 6 September
     * *** >>> What ------------>>> SystemClose()
     * *** >>> Why ------------->>>
     * *** >>> Parameters ------>>> no
     * *** >>> Status ---------->>>
     */
    //>>>>>>>>> System cloce <<<<<<<<<<<   
    void SystemClose() {
        int x = JOptionPane.showConfirmDialog(this, "Do you sure close the System ?", "Exit System", JOptionPane.YES_NO_OPTION);
        if (JOptionPane.YES_OPTION == x) {
            this.dispose();
        } else if (JOptionPane.NO_OPTION == x) {
            setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        }
    }
    //>>>>>>>>> System cloce <<<<<<<<<<<       

//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\ 

//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\ 
    /* *** >>> Date ------------>>> 
     * *** >>> What ------------>>> 
     * *** >>> Why ------------->>> 
     * *** >>> Parameters ------>>>
     * *** >>> Status ---------->>>
     */
//>>>>>>>>> printInvoice <<<<<<<<<<<    
private void printInvoice() {
        
            try {
               // FileInputStream is = new FileInputStream("F:\\SADFInal\\01_1_siddha_System\\src\\Report\\OtherProductTotal.jasper");
                  FileInputStream is = new FileInputStream(SaveFilePath.REPORT_File_path+"\\OtherProductTotal.jasper");
                //    InputStream is = new FileInputStream(SaveFilePath.REPORT_BASE_URL + "reportinvoice.jasper");
                Map<String, Object> map = new HashMap<>();
                map.put("d1_report", d1);  //tx_invoiceid.getText()
                map.put("d2_report", d2); 
                map.put("count", la_nin.getText());
                map.put("nettotal", la_netT.getText());
                
                JasperPrint fileReport = JasperFillManager.fillReport(is, map, DBClass.con());
                //    JasperViewer.viewReport(fileReport, false);
                try {
                    String pathPDF = "";
                    // File file = new File("DDRR.txt");
                    File file = new File(SaveFilePath.REPORT_BASE_URL + "\\DDRR5.txt");
                    if (!file.exists()) {
                        // System.out.println("f");
                        file.createNewFile();
                        FileWriter fr = new FileWriter(file);

                        JFileChooser jfc = new JFileChooser();
                        jfc.setDialogType(JFileChooser.CUSTOM_DIALOG);
                        jfc.setMultiSelectionEnabled(false);
                        jfc.showSaveDialog(jfc);
                        pathPDF = jfc.getSelectedFile().getPath().replace("\\", "\\\\");

                        fr.write("DB.map_prTotal=" + pathPDF);
                        fr.close();
                        File pF = new File(pathPDF);
                        pF.mkdir();
                    }

                    InputStream input = new FileInputStream(SaveFilePath.REPORT_BASE_URL + "\\DDRR5.txt");
                    Properties prop = new Properties();
                    prop.load(input);
                    pathPDF = prop.getProperty("DB.map_prTotal");
                    //  System.out.println(prop.getProperty("DB.mpa"));

                    JasperExportManager.exportReportToPdfFile(fileReport, pathPDF + "\\" +d1+"_"+t1+"_"+d2+"_"+" _ Other Product Total.pdf");
                    JasperPrintManager.printReport(fileReport, false);
//   JasperExportManager.exportReportToXmlFile(fileReport, pathPDF + "\\\\" + GenaratorXMLName(tx_refno_jLayeredPane_invoice.getText()),true);
                    // System.out.println(pathPDF + "\\\\" + GenaratorPDFName(tx_refno_jLayeredPane_invoice.getText()));
                } catch (IOException e) {
                    systemLogger.initLogger(protoal.class).error("printInvoice() IOException Error",e);
                    // e.printStackTrace();
                    JOptionPane.showMessageDialog(null, "PDF not save printInvoice!!! \n ", "Error Massage", JOptionPane.ERROR_MESSAGE);
                }

                

            } catch (JRException e) {
                systemLogger.initLogger(protoal.class).error("printInvoice() JRException Error",e);
                JOptionPane.showMessageDialog(null, "Repot Not Compleate , Please Check It printInvoice!!!", "Report Error", JOptionPane.ERROR_MESSAGE);
            } catch (Exception e) {
                systemLogger.initLogger(protoal.class).error("printInvoice() Exception Error",e);
                // e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Repoting Error printInvoice!!!", "Report Error", JOptionPane.ERROR_MESSAGE);
            }
        

    }
//>>>>>>>>> printInvoice <<<<<<<<<<<         

//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\ 
    /* *** >>> Date ------------>>> 
     * *** >>> What ------------>>> 
     * *** >>> Why ------------->>> 
     * *** >>> Parameters ------>>>
     * *** >>> Status ---------->>>
     */
//>>>>>>>>> netToatl <<<<<<<<<<<  
private void netToatl() {
    int numnrow = jTable_d_a.getRowCount();
    double nt = 0;
    for(int i=0;i<numnrow;i++){
        double val = Double.valueOf(jTable_d_a.getValueAt(i, 5).toString());
        nt += val;
    }
    la_netT.setText(""+nt);
    la_nin.setText(""+numnrow);
}
//>>>>>>>>> netToatl <<<<<<<<<<<         

//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\ 
  //---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\ 
    /* *** >>> Date ------------>>> 
     * *** >>> What ------------>>> Singltan class 
     * *** >>> Why ------------->>> ek object ekk hdnn
     * *** >>> Parameters ------>>>
     * *** >>> Status ---------->>>
     */
//>>>>>>>>> Get Instance <<<<<<<<<<<  
    private static final protoal doctor = new protoal();

    public static protoal getCallPopup() {
        return doctor;
    }
//>>>>>>>>> Get Instance <<<<<<<<<<<         

//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\ 
}
