/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CHETHANA
 */
public class stock extends javax.swing.JFrame {
UniversalMethod u = new UniversalMethod();
public static int idsearch;
    public stock() {
        initComponents();
         systemLogger.initLogger(stock.class).info("Open Stock Frme");
         u.imageMethod(background, home_la_uesr_image, doctor_la_login_use_name, agent_la_home_img, login_la_mini, login_la_cloce);
          cleareFields();
          doctor_la_login_use_name.setText(UniversalMethod.getLogUser());
          u.imageMethod("/img/grnlist1.png", jLabel3);
            u.imageMethod("/img/newB.png", stock_la_new);
            u.imageMethod("/img/search.png", stock_la_search);
          
            stock_la_new.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agent_la_date = new javax.swing.JLabel();
        agent_la_time = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        agent_la_home_img = new javax.swing.JLabel();
        doctor_la_login_use_name = new javax.swing.JLabel();
        home_la_uesr_image = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        login_la_mini = new javax.swing.JLabel();
        login_la_cloce = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tx_barcode = new javax.swing.JTextField();
        tx_item_name = new javax.swing.JTextField();
        tx_item_id = new javax.swing.JTextField();
        tx_shortname = new javax.swing.JTextField();
        tx_oldnew = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        stock_la_search = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_stock = new javax.swing.JTable();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        stock_la_new = new javax.swing.JLabel();
        tx_mf = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        tx_ex = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        tx_isactive = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        tx_qty = new javax.swing.JTextField();
        tx_buyprice = new javax.swing.JTextField();
        tx_sellprice = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        tx_subcatogery = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1380, 768));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1380, 768));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(null);

        agent_la_date.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        agent_la_date.setForeground(new java.awt.Color(255, 255, 255));
        agent_la_date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agent_la_date.setText("Invoice");
        agent_la_date.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(agent_la_date);
        agent_la_date.setBounds(10, 5, 130, 35);

        agent_la_time.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        agent_la_time.setForeground(new java.awt.Color(255, 255, 255));
        agent_la_time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agent_la_time.setText("Invoice");
        agent_la_time.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(agent_la_time);
        agent_la_time.setBounds(150, 5, 130, 35);

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(280, 5, 20, 30);

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(140, 5, 20, 30);

        agent_la_home_img.setText("jLabel1");
        agent_la_home_img.setRequestFocusEnabled(false);
        agent_la_home_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agent_la_home_imgMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                agent_la_home_imgMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                agent_la_home_imgMouseExited(evt);
            }
        });
        getContentPane().add(agent_la_home_img);
        agent_la_home_img.setBounds(600, 5, 80, 30);

        doctor_la_login_use_name.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        doctor_la_login_use_name.setForeground(new java.awt.Color(255, 255, 255));
        doctor_la_login_use_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        doctor_la_login_use_name.setText("Invoice");
        getContentPane().add(doctor_la_login_use_name);
        doctor_la_login_use_name.setBounds(330, 5, 260, 35);

        home_la_uesr_image.setText("userlogo");
        getContentPane().add(home_la_uesr_image);
        home_la_uesr_image.setBounds(290, 10, 30, 30);

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(580, 5, 20, 30);

        jLabel1.setBackground(new java.awt.Color(51, 204, 255));
        jLabel1.setFont(new java.awt.Font("Eras Bold ITC", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("STOCK");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(760, 1, 330, 40);

        login_la_mini.setBackground(new java.awt.Color(255, 255, 255));
        login_la_mini.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        login_la_mini.setForeground(new java.awt.Color(0, 0, 0));
        login_la_mini.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_la_mini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_la_miniMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                login_la_miniMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                login_la_miniMouseExited(evt);
            }
        });
        getContentPane().add(login_la_mini);
        login_la_mini.setBounds(1295, 10, 30, 30);

        login_la_cloce.setBackground(new java.awt.Color(255, 255, 255));
        login_la_cloce.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        login_la_cloce.setForeground(new java.awt.Color(0, 0, 0));
        login_la_cloce.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_la_cloce.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_la_cloceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                login_la_cloceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                login_la_cloceMouseExited(evt);
            }
        });
        getContentPane().add(login_la_cloce);
        login_la_cloce.setBounds(1330, 10, 30, 30);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 43, 1370, 2);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Barcode");
        jLabel4.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 80, 160, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(":");
        jLabel5.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(200, 80, 30, 30);

        tx_barcode.setBackground(new java.awt.Color(235, 228, 228));
        tx_barcode.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tx_barcode.setForeground(new java.awt.Color(0, 0, 0));
        tx_barcode.setText("jTextField1");
        tx_barcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tx_barcodeKeyPressed(evt);
            }
        });
        getContentPane().add(tx_barcode);
        tx_barcode.setBounds(220, 80, 290, 33);

        tx_item_name.setBackground(new java.awt.Color(235, 228, 228));
        tx_item_name.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tx_item_name.setForeground(new java.awt.Color(0, 0, 0));
        tx_item_name.setText("jTextField1");
        getContentPane().add(tx_item_name);
        tx_item_name.setBounds(220, 125, 290, 33);

        tx_item_id.setBackground(new java.awt.Color(235, 228, 228));
        tx_item_id.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tx_item_id.setForeground(new java.awt.Color(0, 0, 0));
        tx_item_id.setText("jTextField1");
        getContentPane().add(tx_item_id);
        tx_item_id.setBounds(220, 170, 290, 33);

        tx_shortname.setBackground(new java.awt.Color(235, 228, 228));
        tx_shortname.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tx_shortname.setForeground(new java.awt.Color(0, 0, 0));
        tx_shortname.setText("jTextField1");
        getContentPane().add(tx_shortname);
        tx_shortname.setBounds(220, 215, 290, 33);

        tx_oldnew.setBackground(new java.awt.Color(235, 228, 228));
        tx_oldnew.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tx_oldnew.setForeground(new java.awt.Color(0, 0, 0));
        tx_oldnew.setText("jTextField1");
        getContentPane().add(tx_oldnew);
        tx_oldnew.setBounds(750, 80, 210, 33);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText(":");
        jLabel13.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel13);
        jLabel13.setBounds(730, 80, 30, 30);

        jLabel15.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText(":");
        jLabel15.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel15);
        jLabel15.setBounds(200, 215, 30, 30);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText(":");
        jLabel9.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel9);
        jLabel9.setBounds(200, 170, 30, 30);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(":");
        jLabel7.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(200, 125, 30, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Item Name");
        jLabel6.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 125, 160, 30);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Item ID");
        jLabel8.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 170, 160, 30);

        jLabel14.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Short Name");
        jLabel14.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel14);
        jLabel14.setBounds(40, 215, 160, 30);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("New Old");
        jLabel12.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel12);
        jLabel12.setBounds(570, 80, 160, 30);

        stock_la_search.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        stock_la_search.setForeground(new java.awt.Color(0, 0, 0));
        stock_la_search.setText("Search");
        stock_la_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stock_la_searchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                stock_la_searchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                stock_la_searchMouseExited(evt);
            }
        });
        getContentPane().add(stock_la_search);
        stock_la_search.setBounds(220, 330, 120, 40);

        jTable_stock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stock ID", "Item ID", "Short  Name", "Barcode", "Item Name", "NewOld", "Sub Catogery", "QTY", "Buy Price", "Sell Price", "MF Date", "EX Date", "Is Active"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_stock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_stockMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_stock);
        if (jTable_stock.getColumnModel().getColumnCount() > 0) {
            jTable_stock.getColumnModel().getColumn(0).setMinWidth(70);
            jTable_stock.getColumnModel().getColumn(0).setPreferredWidth(70);
            jTable_stock.getColumnModel().getColumn(0).setMaxWidth(70);
            jTable_stock.getColumnModel().getColumn(1).setMinWidth(70);
            jTable_stock.getColumnModel().getColumn(1).setPreferredWidth(70);
            jTable_stock.getColumnModel().getColumn(1).setMaxWidth(70);
            jTable_stock.getColumnModel().getColumn(2).setMinWidth(180);
            jTable_stock.getColumnModel().getColumn(2).setPreferredWidth(180);
            jTable_stock.getColumnModel().getColumn(2).setMaxWidth(180);
            jTable_stock.getColumnModel().getColumn(4).setMinWidth(250);
            jTable_stock.getColumnModel().getColumn(4).setPreferredWidth(250);
            jTable_stock.getColumnModel().getColumn(4).setMaxWidth(250);
            jTable_stock.getColumnModel().getColumn(5).setMinWidth(70);
            jTable_stock.getColumnModel().getColumn(5).setPreferredWidth(70);
            jTable_stock.getColumnModel().getColumn(5).setMaxWidth(70);
            jTable_stock.getColumnModel().getColumn(7).setMinWidth(80);
            jTable_stock.getColumnModel().getColumn(7).setPreferredWidth(80);
            jTable_stock.getColumnModel().getColumn(7).setMaxWidth(80);
            jTable_stock.getColumnModel().getColumn(12).setMinWidth(70);
            jTable_stock.getColumnModel().getColumn(12).setPreferredWidth(70);
            jTable_stock.getColumnModel().getColumn(12).setMaxWidth(70);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 410, 1350, 350);

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator5);
        jSeparator5.setBounds(0, 320, 1370, 10);

        jLabel3.setText("grn");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(1020, 330, 130, 40);

        stock_la_new.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        stock_la_new.setForeground(new java.awt.Color(0, 0, 0));
        stock_la_new.setText("New");
        stock_la_new.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stock_la_newMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                stock_la_newMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                stock_la_newMouseExited(evt);
            }
        });
        getContentPane().add(stock_la_new);
        stock_la_new.setBounds(380, 330, 120, 40);

        tx_mf.setBackground(new java.awt.Color(235, 228, 228));
        tx_mf.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tx_mf.setForeground(new java.awt.Color(0, 0, 0));
        tx_mf.setText("jTextField1");
        getContentPane().add(tx_mf);
        tx_mf.setBounds(1160, 80, 170, 33);

        jLabel16.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("MF Date");
        jLabel16.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel16);
        jLabel16.setBounds(1020, 80, 110, 30);

        jLabel18.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText(":");
        jLabel18.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel18);
        jLabel18.setBounds(1130, 80, 30, 30);

        jLabel19.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("EX Date");
        jLabel19.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel19);
        jLabel19.setBounds(1020, 130, 110, 30);

        jLabel20.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText(":");
        jLabel20.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel20);
        jLabel20.setBounds(1130, 130, 30, 30);

        tx_ex.setBackground(new java.awt.Color(235, 228, 228));
        tx_ex.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tx_ex.setForeground(new java.awt.Color(0, 0, 0));
        tx_ex.setText("jTextField1");
        getContentPane().add(tx_ex);
        tx_ex.setBounds(1160, 130, 170, 33);

        jLabel21.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText(":");
        jLabel21.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel21);
        jLabel21.setBounds(1130, 180, 30, 30);

        tx_isactive.setBackground(new java.awt.Color(235, 228, 228));
        tx_isactive.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tx_isactive.setForeground(new java.awt.Color(0, 0, 0));
        tx_isactive.setText("jTextField1");
        getContentPane().add(tx_isactive);
        tx_isactive.setBounds(1160, 180, 170, 33);

        jLabel23.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Is Acrive");
        jLabel23.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel23);
        jLabel23.setBounds(1020, 180, 110, 30);

        tx_qty.setBackground(new java.awt.Color(235, 228, 228));
        tx_qty.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tx_qty.setForeground(new java.awt.Color(0, 0, 0));
        tx_qty.setText("jTextField1");
        getContentPane().add(tx_qty);
        tx_qty.setBounds(750, 180, 210, 33);

        tx_buyprice.setBackground(new java.awt.Color(235, 228, 228));
        tx_buyprice.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tx_buyprice.setForeground(new java.awt.Color(0, 0, 0));
        tx_buyprice.setText("jTextField1");
        getContentPane().add(tx_buyprice);
        tx_buyprice.setBounds(750, 230, 210, 33);

        tx_sellprice.setBackground(new java.awt.Color(235, 228, 228));
        tx_sellprice.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tx_sellprice.setForeground(new java.awt.Color(0, 0, 0));
        tx_sellprice.setText("jTextField1");
        getContentPane().add(tx_sellprice);
        tx_sellprice.setBounds(750, 280, 210, 33);

        jLabel28.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Sub Catogery");
        jLabel28.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel28);
        jLabel28.setBounds(570, 130, 160, 30);

        jLabel29.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText(":");
        jLabel29.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel29);
        jLabel29.setBounds(730, 180, 30, 30);

        jLabel30.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText(":");
        jLabel30.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel30);
        jLabel30.setBounds(730, 230, 30, 30);

        jLabel31.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText(":");
        jLabel31.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel31);
        jLabel31.setBounds(730, 130, 30, 30);

        jLabel33.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText(":");
        jLabel33.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel33);
        jLabel33.setBounds(730, 280, 30, 30);

        jLabel34.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("QTY");
        jLabel34.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel34);
        jLabel34.setBounds(570, 180, 160, 30);

        jLabel35.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Sell Price");
        jLabel35.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel35);
        jLabel35.setBounds(570, 280, 160, 30);

        tx_subcatogery.setBackground(new java.awt.Color(235, 228, 228));
        tx_subcatogery.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tx_subcatogery.setForeground(new java.awt.Color(0, 0, 0));
        tx_subcatogery.setText("jTextField1");
        getContentPane().add(tx_subcatogery);
        tx_subcatogery.setBounds(750, 130, 210, 33);

        jLabel37.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Buy Price");
        jLabel37.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel37);
        jLabel37.setBounds(570, 230, 160, 30);

        background.setBackground(new java.awt.Color(234, 232, 232));
        background.setForeground(new java.awt.Color(255, 255, 255));
        background.setText("jLabel1");
        getContentPane().add(background);
        background.setBounds(0, 0, 1380, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agent_la_home_imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agent_la_home_imgMouseClicked
         if(UniversalMethod.getuserType().equals("Admin") | UniversalMethod.getuserType().equals("Maneger") ){
            int x = JOptionPane.showConfirmDialog(this, "Do you sure Go to The Home ?", "Change Interface", JOptionPane.YES_NO_OPTION);
            if (JOptionPane.YES_OPTION == x) {
                    home.getCallPopup().setVisible(true);
                    this.dispose();
             } else if (JOptionPane.NO_OPTION == x) {
                 setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
                 tx_barcode.grabFocus();
             }
        }else if( UniversalMethod.getuserType().equals("Stock Keeper")){
             int x = JOptionPane.showConfirmDialog(this, "Do you sure Go to The Home ?", "Change Interface", JOptionPane.YES_NO_OPTION);
            if (JOptionPane.YES_OPTION == x) {
                    home_stock.getCallPopup().setVisible(true);
                    this.dispose();
             } else if (JOptionPane.NO_OPTION == x) {
                 setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
                 tx_barcode.grabFocus();
             }
        }
    }//GEN-LAST:event_agent_la_home_imgMouseClicked

    private void agent_la_home_imgMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agent_la_home_imgMouseEntered
        u.imageMethod("/img/home_2_2.png", agent_la_home_img);
    }//GEN-LAST:event_agent_la_home_imgMouseEntered

    private void agent_la_home_imgMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agent_la_home_imgMouseExited
        u.imageMethod("/img/home_.png", agent_la_home_img);
    }//GEN-LAST:event_agent_la_home_imgMouseExited

    private void login_la_miniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_la_miniMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_login_la_miniMouseClicked

    private void login_la_miniMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_la_miniMouseEntered
        //    ltx_barcode.setBackground(Color.gray);
        u.imageMethod("/img/mini2.png", login_la_mini);
    }//GEN-LAST:event_login_la_miniMouseEntered

    private void login_la_miniMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_la_miniMouseExited
        //    login_la_mini.setBackground(Color.white);
        u.imageMethod("/img/mini.png", login_la_mini);
    }//GEN-LAST:event_login_la_miniMouseExited

    private void login_la_cloceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_la_cloceMouseClicked
        SystemClose();
    }//GEN-LAST:event_login_la_cloceMouseClicked

    private void login_la_cloceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_la_cloceMouseEntered
        //    login_la_cloce.setBackground(Color.red);
        u.imageMethod("/img/exti.png", login_la_cloce);
    }//GEN-LAST:event_login_la_cloceMouseEntered

    private void login_la_cloceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_la_cloceMouseExited
        //    login_la_cloce.setBackground(Color.white);
        u.imageMethod("/img/exti2.png", login_la_cloce);
    }//GEN-LAST:event_login_la_cloceMouseExited

    private void stock_la_searchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stock_la_searchMouseEntered
        u.imageMethod("/img/search2.png", stock_la_search );
    }//GEN-LAST:event_stock_la_searchMouseEntered

    private void stock_la_searchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stock_la_searchMouseExited
        u.imageMethod("/img/search.png", stock_la_search );
    }//GEN-LAST:event_stock_la_searchMouseExited

    private void stock_la_newMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stock_la_newMouseClicked
        u.imageMethod("/img/newB2.png", stock_la_new);
        stock_la_new.setVisible(false);
        cleareFields();
    }//GEN-LAST:event_stock_la_newMouseClicked

    private void stock_la_newMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stock_la_newMouseEntered
        u.imageMethod("/img/newB2.png", stock_la_new);
    }//GEN-LAST:event_stock_la_newMouseEntered

    private void stock_la_newMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stock_la_newMouseExited
        u.imageMethod("/img/newB.png", stock_la_new);
    }//GEN-LAST:event_stock_la_newMouseExited

    private void jTable_stockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_stockMouseClicked
       DefaultTableModel defTabMod = (DefaultTableModel) jTable_stock.getModel();
       stock_la_new.setVisible(true);
        idsearch = Integer.parseInt(defTabMod.getValueAt(jTable_stock.getSelectedRow(), 3).toString());
        tx_item_id.setText(defTabMod.getValueAt(jTable_stock.getSelectedRow(), 1).toString());
        tx_shortname.setText(defTabMod.getValueAt(jTable_stock.getSelectedRow(), 2).toString());
        tx_barcode.setText(defTabMod.getValueAt(jTable_stock.getSelectedRow(), 3).toString());
        tx_item_name.setText(defTabMod.getValueAt(jTable_stock.getSelectedRow(), 4).toString());
        tx_oldnew.setText(defTabMod.getValueAt(jTable_stock.getSelectedRow(), 5).toString());
        tx_subcatogery.setText(defTabMod.getValueAt(jTable_stock.getSelectedRow(), 6).toString());
        tx_qty.setText(defTabMod.getValueAt(jTable_stock.getSelectedRow(), 7).toString());
        tx_buyprice.setText(defTabMod.getValueAt(jTable_stock.getSelectedRow(), 8).toString());
        tx_sellprice.setText(defTabMod.getValueAt(jTable_stock.getSelectedRow(), 9).toString());
        tx_mf.setText(defTabMod.getValueAt(jTable_stock.getSelectedRow(), 10).toString());
        tx_ex.setText(defTabMod.getValueAt(jTable_stock.getSelectedRow(), 11).toString());
        tx_isactive.setText(defTabMod.getValueAt(jTable_stock.getSelectedRow(), 12).toString());
        
    }//GEN-LAST:event_jTable_stockMouseClicked

    private void stock_la_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stock_la_searchMouseClicked
       u.imageMethod("/img/search2.png", stock_la_search );
        if (idsearch != 0 | !tx_barcode.getText().trim().isEmpty()) {
        searchStock_barcode();
        } else {
      JOptionPane.showMessageDialog(null, "Error Not Selected The Stock Item  !!! \n searchStock() \n" , "Error Massage", JOptionPane.ERROR_MESSAGE);
        tx_barcode.grabFocus();
        }
    }//GEN-LAST:event_stock_la_searchMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        grnlist.getCallPopup(this).setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        u.imageMethod("/img/grnlist2.png", jLabel3);
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
         u.imageMethod("/img/grnlist1.png", jLabel3);
    }//GEN-LAST:event_jLabel3MouseExited

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_F2){
            if(tx_barcode.getText().trim().isEmpty()){
                tx_barcode.grabFocus();
            }else{
                searchStock_barcode();
            }
        }
    }//GEN-LAST:event_formKeyPressed

    private void tx_barcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tx_barcodeKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_F2){
            if(tx_barcode.getText().trim().isEmpty()){
                tx_barcode.grabFocus();
            }else{
                searchStock_barcode();
            }
        }
    }//GEN-LAST:event_tx_barcodeKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agent_la_date;
    private javax.swing.JLabel agent_la_home_img;
    private javax.swing.JLabel agent_la_time;
    private javax.swing.JLabel background;
    private javax.swing.JLabel doctor_la_login_use_name;
    private javax.swing.JLabel home_la_uesr_image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable jTable_stock;
    private javax.swing.JLabel login_la_cloce;
    private javax.swing.JLabel login_la_mini;
    private javax.swing.JLabel stock_la_new;
    private javax.swing.JLabel stock_la_search;
    private javax.swing.JTextField tx_barcode;
    private javax.swing.JTextField tx_buyprice;
    private javax.swing.JTextField tx_ex;
    private javax.swing.JTextField tx_isactive;
    private javax.swing.JTextField tx_item_id;
    private javax.swing.JTextField tx_item_name;
    private javax.swing.JTextField tx_mf;
    private javax.swing.JTextField tx_oldnew;
    private javax.swing.JTextField tx_qty;
    private javax.swing.JTextField tx_sellprice;
    private javax.swing.JTextField tx_shortname;
    private javax.swing.JTextField tx_subcatogery;
    // End of variables declaration//GEN-END:variables


           


//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\ 
    /* *** >>> Date ------------>>> mon 6 September
     * *** >>> What ------------>>> SystemClose()
     * *** >>> Why ------------->>>
     * *** >>> Parameters ------>>> no
     * *** >>> Status ---------->>>
     */
    //>>>>>>>>> System cloce <<<<<<<<<<<   
    void SystemClose() {
        int x = JOptionPane.showConfirmDialog(this, "Do you sure close the System ?", "Exit System", JOptionPane.YES_NO_OPTION);
        if (JOptionPane.YES_OPTION == x) {
            // setDefaultCloseOperation(EXIT_ON_CLOSE);
            u.insertUserClose(tx_barcode,agent_la_date.getText(), agent_la_time.getText());
            System.exit(0);
        } else if (JOptionPane.NO_OPTION == x) {
            setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
            login_la_cloce.setBackground(new Color(153, 204, 255));
        }
    }
    //>>>>>>>>> System cloce <<<<<<<<<<<       

//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\  

//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\ 
    /* *** >>> Date ------------>>> 
     * *** >>> What ------------>>> Singltan class 
     * *** >>> Why ------------->>> ek object ekk hdnn
     * *** >>> Parameters ------>>>
     * *** >>> Status ---------->>>
     */
    //>>>>>>>>> Get Instance <<<<<<<<<<<  
    private static final stock stoc = new stock();
    public static stock getCallPopup() {
        return stoc;
    }
//>>>>>>>>> Get Instance <<<<<<<<<<<         

//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\    

 //---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\ 
    /* *** >>> Date ------------>>> 
     * *** >>> What ------------>>>  
     * *** >>> Why ------------->>>
     * *** >>> Parameters ------>>>
     * *** >>> Status ---------->>>
     */
//>>>>>>>>> cleareFields <<<<<<<<<<<      
    private void cleareFields() {
        tx_barcode.setText(null);
        tx_item_id.setText(null);
        tx_shortname.setText(null);
        tx_item_name.setText(null);
        tx_oldnew.setText(null);
        tx_subcatogery.setText(null);
        tx_qty.setText(null);
        tx_buyprice.setText(null);
        tx_sellprice.setText(null);
        tx_mf.setText(null);
        tx_ex.setText(null);
        tx_isactive.setText(null);
        
        idsearch = 0;
        tx_item_id.setEditable(false);
        tx_shortname.setEditable(false);
        tx_item_name.setEditable(false);
        tx_oldnew.setEditable(false);
        tx_subcatogery.setEditable(false);
        tx_qty.setEditable(false);
        tx_buyprice.setEditable(false);
        tx_sellprice.setEditable(false);
        tx_mf.setEditable(false);
        tx_ex.setEditable(false);
        tx_isactive.setEditable(false);
        stock_la_new.setVisible(true);
        searchStock();
    }
//>>>>>>>>> cleareFields <<<<<<<<<<<         

//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\ 

//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\ 
    /* *** >>> Date ------------>>> 
     * *** >>> What ------------>>>  
     * *** >>> Why ------------->>> 
     * *** >>> Parameters ------>>>
     * *** >>> Status ---------->>>
     */
//>>>>>>>>> searchStock_barcode <<<<<<<<<<<      
    private void searchStock_barcode() {
        try {
             DefaultTableModel defTabMod = (DefaultTableModel) jTable_stock.getModel();
             defTabMod.getDataVector().removeAllElements();
          //  ResultSet rs = DBClass.getData("select * from supplier where idsupplier  ='" + tx_doctor_id.getText() + "' order by iddoctor");
          //  DBClass.getData("select * from stock where barcode like '" + tx_barcode.getText() + "%' order by idstock");
            DBClass.getData("select st.idstock,st.iditem,st.qty,st.newold,st.expdate,st.mandate,st.buying_price,st.sell_price,st.status,"
                    + "it.barcode,it.itemname,it.shortname,isc.terms from stock st,item it,itemsubcatogery isc  "
                    + "where st.iditem=it.iditem and it.iditemsubcatogery=isc.iditemsubcatogery and it.barcode like '" + tx_barcode.getText() + "%' order by st.idstock");
           
            if (DBClass.r.isBeforeFirst() == true) {
                while (DBClass.r.next()) {
                     Vector v = new Vector();
                    v.add(DBClass.r.getString("st.idstock"));
                    v.add(DBClass.r.getString("st.iditem"));
                    
                    v.add(DBClass.r.getString("it.shortname"));
                    v.add(DBClass.r.getString("it.barcode"));
                    v.add(DBClass.r.getString("it.itemname"));
                    
                    v.add(DBClass.r.getString("st.newold"));
                    
                    v.add(DBClass.r.getString("isc.terms"));
                    
                    v.add(DBClass.r.getString("st.qty"));
                    
                    tableRowColor(Integer.parseInt(DBClass.r.getString("st.qty")));
                    
                    v.add(DBClass.r.getString("st.buying_price"));
                    v.add(DBClass.r.getString("st.sell_price"));
                    v.add(DBClass.r.getString("st.mandate"));
                    v.add(DBClass.r.getString("st.expdate"));
                    
                    if (DBClass.r.getInt("st.status") == 1) {
                        v.add("Active");
                        defTabMod.addRow(v);
                    } else {
                        v.add("Inactive");
                        defTabMod.addRow(v);
                    }
                    stock_la_new.setVisible(true);
                }
            }
            
        } catch (Exception ex) {
             systemLogger.initLogger(stock.class).error("searchStock_barcode()  Error",ex);
 JOptionPane.showMessageDialog(null, "Error StockTableSearchBarcode !!! \n" , "Error Massage", JOptionPane.ERROR_MESSAGE);
     }
    }
    //>>>>>>>>> searchStock_barcode <<<<<<<<<<<         

//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\    

//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\ 
    /* *** >>> Date ------------>>> 
     * *** >>> What ------------>>>  
     * *** >>> Why ------------->>> 
     * *** >>> Parameters ------>>>
     * *** >>> Status ---------->>>
     */
//>>>>>>>>> searchStock <<<<<<<<<<<      
    private void searchStock() {
        try {
             DefaultTableModel defTabMod = (DefaultTableModel) jTable_stock.getModel();
             defTabMod.getDataVector().removeAllElements();
          //  ResultSet rs = DBClass.getData("select * from supplier where idsupplier  ='" + tx_doctor_id.getText() + "' order by iddoctor");
          //  DBClass.getData("select * from stock where barcode like '" + tx_barcode.getText() + "%' order by idstock");
            DBClass.getData("select st.idstock,st.iditem,st.qty,st.newold,st.expdate,st.mandate,st.buying_price,st.sell_price,st.status,"
                    + "it.barcode,it.itemname,it.shortname,isc.terms from stock st,item it,itemsubcatogery isc  "
                    + "where st.iditem=it.iditem and it.iditemsubcatogery=isc.iditemsubcatogery order by st.idstock");
           
            if (DBClass.r.isBeforeFirst() == true) {
                while (DBClass.r.next()) {
                     Vector v = new Vector();
                    v.add(DBClass.r.getString("st.idstock"));
                    v.add(DBClass.r.getString("st.iditem"));
                    
                    v.add(DBClass.r.getString("it.shortname"));
                    v.add(DBClass.r.getString("it.barcode"));
                    v.add(DBClass.r.getString("it.itemname"));
                    
                    v.add(DBClass.r.getString("st.newold"));
                    
                    v.add(DBClass.r.getString("isc.terms"));
                    
                    v.add(DBClass.r.getString("st.qty"));
                    
                    tableRowColor(Integer.parseInt(DBClass.r.getString("st.qty")));
                    
                    v.add(DBClass.r.getString("st.buying_price"));
                    v.add(DBClass.r.getString("st.sell_price"));
                    v.add(DBClass.r.getString("st.mandate"));
                    v.add(DBClass.r.getString("st.expdate"));
                    
                    if (DBClass.r.getInt("st.status") == 1) {
                        v.add("Active");
                        defTabMod.addRow(v);
                    } else {
                        v.add("Inactive");
                        defTabMod.addRow(v);
                    }
                   
                }
            }
            
        } catch (Exception ex) {
             systemLogger.initLogger(stock.class).error("searchStock()All  Error",ex);
 JOptionPane.showMessageDialog(null, "Error StockTableSearch All !!! \n" , "Error Massage", JOptionPane.ERROR_MESSAGE);
     }
    }
    //>>>>>>>>> searchStock <<<<<<<<<<<         

//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\ 
    /* *** >>> Date ------------>>> 
     * *** >>> What ------------>>>  
     * *** >>> Why ------------->>> 
     * *** >>> Parameters ------>>>
     * *** >>> Status ---------->>>
     */
//>>>>>>>>> tableRowColor <<<<<<<<<<<      
    private void tableRowColor(int ValueI) {
        jTable_stock.setDefaultRenderer(Object.class,new DefaultTableCellRenderer(){
            @Override
            public Component getTableCellRendererComponent(JTable table,Object value,boolean isSelected,boolean hasFocus,int row,int column){
            JLabel label = (JLabel) super.getTableCellRendererComponent(table,value,isSelected,hasFocus,row,column);
            //***********************************
//                Color c = Color.WHITE;
//                Object texto = table.getValueAt(row, 12);
//                if(texto != null && ValueI.equals(texto.toString())){
//                    c = Color.RED;
//                    label.setBackground(c);
//                    jTable_stock.setSelectionForeground(Color.GREEN);
//                }
            //***********************************
////                Color c = Color.WHITE;
////                Object texto = table.getValueAt(row, 7);
////            //   if(texto != null && ValueI >= (Integer.parseInt(texto.toString()))){
////              if( ValueI <= (Integer.parseInt(texto.toString()))){
////            //    if(texto != null && ValueI >= 50){
////                    c = Color.RED;
////                    label.setBackground(c);
////                    jTable_stock.setSelectionForeground(Color.GREEN);
////                }
            //***********************************
                
             //***********************************    
            return label;
            }
        });
    }
    //>>>>>>>>> tableRowColor <<<<<<<<<<<         

//---------########---------*********************---------########---------*********************---------########---------\\ 
//---------########---------*********************---------########---------*********************---------########---------\\    
//---------########---------*********************---------########---------*********************---------########---------\\    

    
}
